# -*- coding: utf-8 -*-
"""steam_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjSBxt9UFvfxmE5GAEtPv1-CQX8DXLNQ
"""

!pip install pandas numpy scipy scikit-learn

review_path = "/content/drive/MyDrive/australian_user_reviews.json"
game_path = "/content/drive/MyDrive/australian_users_items.json"

import os

print(os.path.exists(review_path))
print(os.path.exists(game_path))

import gzip
import json
import pandas as pd

def parse_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    yield json.loads(line)
                except json.JSONDecodeError as e:
                    print(f"Skipping malformed JSON line: {line}. Error: {e}")
                    continue

# -------------------------------
# Create recommendations.csv
# -------------------------------
review_data = []

# Changed to parse_json as the file is not gzipped
for d in parse_json(review_path):
    try:
        user_id = str(d.get('user_id'))
        app_id = str(d.get('item_id'))
        recommend = d.get('recommend')

        if user_id and app_id:
            review_data.append([user_id, app_id, 1 if recommend else 0])
    except Exception as e:
        print(f"Skipping review data due to error: {e}. Data: {d}")
        continue

recommendations = pd.DataFrame(review_data, columns=['user_id', 'app_id', 'is_recommended'])
recommendations.to_csv("/content/recommendations.csv", index=False)

print("✅ recommendations.csv created")

import json
import pandas as pd
import ast # Import the Abstract Syntax Tree module

def parse_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    # Attempt to parse as a Python literal, which handles single quotes
                    yield ast.literal_eval(line)
                except (ValueError, SyntaxError) as e:
                    print(f"Skipping malformed line (not a valid Python literal): {line}. Error: {e}")
                    continue

review_data = []

for d in parse_json(review_path):
    user_id = str(d.get('user_id'))

    # 🔥 FIX: loop inside reviews list
    for review in d.get('reviews', []):
        try:
            app_id = str(review.get('item_id'))
            recommend = review.get('recommend')

            if user_id and app_id:
                review_data.append([
                    user_id,
                    app_id,
                    1 if recommend else 0
                ])
        except:
            continue

recommendations = pd.DataFrame(
    review_data,
    columns=['user_id', 'app_id', 'is_recommended']
)

print("✅ recommendations shape:", recommendations.shape)
recommendations.head()

game_data = []

# Changed to parse_json as the file is not gzipped
for d in parse_json(game_path):
    try:
        app_id = str(d.get('id'))
        title = d.get('title')

        if app_id and title:
            game_data.append([app_id, title])
    except:
        continue

games = pd.DataFrame(game_data, columns=['app_id', 'title'])
games.to_csv("/content/games.csv", index=False)

print("✅ games.csv created")

import json
import ast # Import the Abstract Syntax Tree module

def parse_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    # Attempt to parse as a Python literal, which handles single quotes
                    yield ast.literal_eval(line)
                except (ValueError, SyntaxError) as e:
                    # If parsing as a Python literal fails, then it's truly malformed
                    print(f"Skipping malformed line (not a valid Python literal): {line}. Error: {e}")
                    continue

# Get the first review using the already defined and validated parse_json function
first_review = next(parse_json(review_path))

print(first_review)

# Get the first game entry using the same parser
first_game = next(parse_json(game_path))

print(first_game)

import pandas as pd

game_data = []

for d in parse_json(game_path):
    for item in d.get('items', []):
        game_data.append([
            str(item['item_id']),
            item['item_name']
        ])

games = pd.DataFrame(game_data, columns=['app_id', 'title'])

# remove duplicates (VERY IMPORTANT)
games = games.drop_duplicates()

print("✅ games extracted:", games.shape)
games.head()

combined_df = pd.merge(recommendations, games, on="app_id")
print(combined_df.shape)
combined_df.head()

import scipy.sparse
import sklearn.metrics as skm

# -------------------------
# Create index mappings
# -------------------------
user_dict = {u: i for i, u in enumerate(combined_df['user_id'].unique())}
game_dict = {g: i for i, g in enumerate(combined_df['app_id'].unique())}

combined_df['user_key'] = combined_df['user_id'].map(user_dict)
combined_df['game_key'] = combined_df['app_id'].map(game_dict)

# -------------------------
# Sparse matrix
# -------------------------
user_game_matrix = scipy.sparse.coo_matrix(
    (combined_df['is_recommended'],
     (combined_df['user_key'], combined_df['game_key']))
)

print("Matrix shape:", user_game_matrix.shape)

# -------------------------
# Recommender function
# -------------------------
def recommend_games(user_id, top_n=5):

    if user_id not in user_dict:
        return "User not found"

    user_idx = user_dict[user_id]

    similarity = skm.pairwise.cosine_similarity(
        user_game_matrix.getrow(user_idx),
        user_game_matrix
    ).ravel()

    similarity[user_idx] = 0

    top_users = similarity.argsort()[::-1][:top_n]

    similar_games = combined_df[
        combined_df['user_key'].isin(top_users)
    ]['app_id']

    seen_games = combined_df[
        combined_df['user_id'] == user_id
    ]['app_id']

    recommendations = similar_games[~similar_games.isin(seen_games)]

    result = combined_df[
        combined_df['app_id'].isin(recommendations)
    ][['title']].drop_duplicates()

    return result.head(10)

def recommend_games(user_id, top_n=10):

    # get numeric index of user
    if user_id not in user_dict:
        return []

    user_idx = user_dict[user_id]

    # similarity
    sim = skm.pairwise.cosine_similarity(user_game_matrix.getrow(user_idx), user_game_matrix).ravel()
    sim[user_idx] = 0

    top_users = sim.argsort()[::-1][:5]

    # games played/recommended by similar users
    games = combined_df[combined_df['user_key'].isin(top_users)]['title']

    # games already seen by user
    seen = combined_df[combined_df['user_key'] == user_idx]['title']

    # IMPORTANT FIX: return real list, not pandas column
    results = games[~games.isin(seen)].drop_duplicates().head(top_n)

    return results.tolist()

test_user = combined_df['user_id'].iloc[0]

print("\n🎮 Steam Recommender System")
print(f"👤 User: {test_user}\n")

results = recommend_games(test_user)

print("🔥 Recommendations:\n")

if len(results) == 0:
    print("No recommendations found.")
else:
    for i, game in enumerate(results, 1):
        print(f"{i}. 🎯 {game}")

